name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        emacs-version: [26.1, 26.2, 26.3, 27.1, 27.2]
        experimental: [false]
        include:
          - emacs-version: snapshot
            experimental: true

    steps:
      - name: setenv
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: conao3/setup-cask@master
        with:
          version: 0.8.6

      - name: install
        run: 'cask install'

      - name: build
        run: 'cask build'

      - name: package
        run: 'cask package'
